### ISSUE TITLE
MindtPy rewrite TODO list

### ISSUE THREAD

**Issue by ZedongPeng** [Pyomo/pyomo#2709]
## Summary
This issue summarizes the TODO list left in MindtPy rewrite #2654 . 

### Description

- [ ] Check and improve the var_list generation in MindtPy. https://github.com/Pyomo/pyomo/pull/2654#discussion_r1042471219
- [ ] Decide whether to remove `feasible_no_good_cuts`. https://github.com/Pyomo/pyomo/pull/2654#discussion_r1042472733
- [ ] Hard-coded value of `zero_tolerance`. https://github.com/Pyomo/pyomo/pull/2654#discussion_r1042541553
- [ ] Redesign the config check in MindtPy. https://github.com/Pyomo/pyomo/pull/2654#discussion_r1042557125
- [ ] Use `StaleFlagManager`. https://github.com/Pyomo/pyomo/pull/2654#discussion_r1046333695
- [ ] Deal with two-sided inequalities. https://github.com/Pyomo/pyomo/pull/2654#discussion_r1048709199
- [ ] Improve the single-tree implementation, especially the `solve_data` design. https://github.com/Pyomo/pyomo/pull/2654#discussion_r1048800267

**Comment by bernalde** [comment]
I will add to this list

- [ ] Support for external function calls in NLP subproblems

**Comment by bernalde** [comment]
I'm also adding links to the relevant comments in previous PRs.
-  https://github.com/Pyomo/pyomo/pull/2654/files/3d01126274de3e3a5beb48d22464083fe6a8fccd#r1054850485
- https://github.com/Pyomo/pyomo/pull/2654/files/3d01126274de3e3a5beb48d22464083fe6a8fccd#r1054854281
- https://github.com/Pyomo/pyomo/pull/2654#discussion_r1099293796
- https://github.com/Pyomo/pyomo/pull/2654#discussion_r1099209447

**Comment by blnicho** [comment]
Comments from @jsiirola's review

- [ ] Fix docstring  https://github.com/Pyomo/pyomo/pull/2654#discussion_r1106102161
- [ ] Use standard Pyomo log handler https://github.com/Pyomo/pyomo/pull/2654#discussion_r1106125117
- [ ] Use of setattr https://github.com/Pyomo/pyomo/pull/2654#discussion_r1106139907
- [ ] Dual sign convention https://github.com/Pyomo/pyomo/pull/2654#discussion_r1106150448

**Comment by bernalde** [comment]
It should also deal with options:

- [ ] LoadSolutions
- [ ] warmstart
- [ ] Change default MIP solver from GLPK to something else?
