### ISSUE TITLE
contrib.alternative_solutions TODO

### ISSUE THREAD

**Issue by emma58** [Pyomo/pyomo#3342]
## Summary

I'm using this issue to compile outstanding improvements for `contrib.alternative_solutions` not addressed in #3270:

- [ ] Transition from APPSI to `contrib.solver`
- [ ] Once solvers are standardized, switch to having users pass in configured solvers rather than separately passing `solver_options` arguments
- [ ] Break `balas.enumerate_binary_solutions` function into smaller functions that can be tested
- [ ] Implement random and norm objectives in `lp_enum`.
- [ ] Add handling for mixed-integer case in `lp_enum_solnpool`
- [ ] Support `variables` argument being something other than `None` in `lp_enum.enumerate_linear_solutions`
- [ ] Refactor `shifted_lp.get_shifted_linear_model` to use the `compile_standard_form` writer from `repn.plugins.standard_form`
- [ ] Refactor `balas` and `obbt` tests to inherit from `unittest.TestCase` and reduce bare assertions.

**Comment by jlgearh** [comment]
Some additional issues include:

- [ ] Add handling for mixed-binary case in lp_enum
- [ ] Do more testing for shifted_lp, specficially check the constraints in the reformulated problem
- [ ] Parallelize the main for loop in obbt 
- [ ] Add more tests to test_lp_enum_solnpool (at least those from test_lp_enum
- [ ] See if the heuristics option can be (re)enabled for lp_enum. This was disabled since Gurobi can produce solutions that are not extreme points during heuristic searches.
- [ ] See if the algorithms can be updated to allow for subsets of variables to explored for lp_enum and lp_enum_solnpool.

**Comment by whart222** [comment]
Some additional issues:

- [ ] Refactor the library to use a custom SolutionPool class.  Return this solution pool class, rather than a list of Solution objects.
- [ ] Develop summary techniques that analyze and visualize a SolutionPool (e.g. consensus patterns)
